### PR TITLE
Tech Fair postponed again

### PR DESCRIPTION
**Pull request by EarthenSky**
Tech Fair had to be postponed again due to the recent picketing from the TSSU strike. The new tech fair date is Nov 15th. 

Attending companies also had to be updated, as some companies could not attend the new date.

### CODE REVIEW

**Comment by modernNeo** [comment]
what does the TSSU strike have to do with the tech fair?

**Comment by modernNeo** [comment]
> as some companies could not attend the new date.

I don't see any companies removed in the HTML?

**Comment by EarthenSky** [comment]
> I don't see any companies removed in the HTML?

They've been commented out for the time being. See `<!-- ... -->` 
Some of the companies have not decided yet whether they'll be attending the new date.

**Comment by EarthenSky** [comment]
> what does the TSSU strike have to do with the tech fair?

It was mainly the picketing that affected the event. We couldn't run any in-person events during picketing because anyone who's in a union isn't morally allowed to cross the picket lines. This includes the employees from the companies we invited.

In addition, the introduction of online classes again meant that few people were showing up to campus anyways, so the event wouldn't have as far of a reach.

**Comment by modernNeo** [comment]
courses are online again cause of TSSU strike or unrelated matter?

**Comment by EarthenSky** [comment]
> courses are online again cause of TSSU strike or unrelated matter?

Unfortunately the TSSU strike was very related, however most courses were only online for 2-3 weeks. Things are back to normal again now that a tentative agreement has been met.

My understanding of the effects of the strike are as follows:
1. For classes where the teacher was in the TSSU, the class was not allowed to run for 3 weeks.
2. For some classes, ~25%, the teachers went on strike in solidarity with the TSSU and didn't run classes for 3 weeks. 
3. For some classes, ~50%, the teachers moved classes online & cancelled up to 2 classes.
4. Finally, the last 25% of classes didn't care and told people to come to school no matter what.

For all classes however, TAs were not allowed to mark any assignments.

**Comment by modernNeo** [comment]
> Unfortunately the TSSU strike was very related, however most courses were only online for 2-3 weeks. Things are back to normal again now that a tentative agreement has been met.

Gotta love how secondary institutions are so quick and easy to roll out online learning during a pandemic or a strike [thereby proving it is a viable alternative] but then pretend that online learning can't match the quality of in person learning [especially ironic for comp sci classes where most of the student learn via the internet anyways].  If there ever was a more clear cut example showing that they care more about their elitism and a justification for the high tuition costs than their students, I can't name it.

**Pull request merged**
