### PR TITLE
Changed Tech Fair event to one day

### PR DESCRIPTION
**Pull request by SpartanApple**

### CODE REVIEW

**Review by modernNeo — CHANGES_REQUESTED** [review]
can you fix these?
https://validator.w3.org/nu/?doc=https%3A%2F%2Fdev.sfucsss.org%2FPR-497%2Fevents%2Ftech_fair%2F2022

https://validator.w3.org/nu/?doc=https%3A%2F%2Fdev.sfucsss.org%2FPR-497%2Fevents%2Ftech_fair%2F2022%2Fmain

**Comment by modernNeo** [comment]
> No.

@SpartanApple can you explain why?

**Comment by modernNeo** [comment]
run the following from your branch
```
git add upstream https://github.com/CSSS/csss-site.git #might need be needed if you already have upstream setup
git pull --rebase upstream master
git push origin Convert_Tech_Fair_OneDay
```

**Review by modernNeo — CHANGES_REQUESTED** [review]
please fix this and I will approve https://validator.w3.org/nu/?doc=https%3A%2F%2Fdev.sfucsss.org%2FPR-497%2Fevents%2Ftech_fair%2F2022%2Fmain

**Comment by SpartanApple** [comment]
@modernNeo done

**Pull request merged**
