### PR TITLE
Tech Fair 2023 Site

### PR DESCRIPTION
**Pull request by EarthenSky**
Just an FYI that I'm working on this year's tech fair website. It's very nearly 100% frontend.

Am quite close to done.

### CODE REVIEW

**Comment by modernNeo** [comment]
> It's very nearly 100% frontend.

I am curious what part of a tech fair website is not front-end 👀

**Comment by EarthenSky** [comment]
@modernNeo W3C validation failed after I made a small change to strings in a .css file (despite it passing validation before), and it looks like the reason it failed is that the dev server didn't spin up fast enough? It's working fine now however https://dev.sfucsss.org/PR-575/events/tech_fair/2023. 

I don't have access to re-running the build in jenkins, do you mind trying to run it again & checking if this was really the issue?

**Comment by modernNeo** [comment]
@EarthenSky will look into it tomorrow.

**Comment by EarthenSky** [comment]
awesome, looks like it's working now! If we could have the site merged by the end of the day on Friday, that would be great! But still no rush

**Comment by modernNeo** [comment]
huh, TIL that a rebase of master triggers a rebuild of all PRs

**Comment by modernNeo** [comment]
did you pull the changes from master into this PR? [not asking you to, just asking if you did]

**Comment by EarthenSky** [comment]
> did you pull the changes from master into this PR? [not asking you to, just asking if you did]

yes I did! as of [here](https://github.com/CSSS/csss-site/pull/575/commits/6ea97498f689a707babb7a824da06895b349d1ce)

**Comment by modernNeo** [comment]
implemented with https://github.com/CSSS/csss-site/pull/607

**Pull request closed without merging**
